name: Check Frozen Release Builds

permissions:
  contents: read

on:
  release:
    types: [published]

jobs:
  check-frozen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch dependencies
        run: cargo fetch

      - name: Build
        run: cargo build --frozen
