name: Snap

on:
  push:
    branches: [ main ]

jobs:
  snap:
    runs-on: ubuntu-18.04

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - uses: snapcore/action-build@v1
      env:
        SNAPCRAFT_BUILD_ENVIRONMENT_MEMORY: 6G
      id: snapcraft

    - uses: actions/upload-artifact@v2
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}

    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.SNAPCRAFT_TOKEN }}
        snap: ${{ steps.snapcraft.outputs.snap }}
