name: Snap

permissions:
  contents: read

on:
  workflow_run:
    workflows: [Build and Test]
    types: [completed]

jobs:
  snap:
    runs-on: ubuntu-20.04
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: snapcore/action-build@v1
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT_MEMORY: 6G
        id: snapcraft

      - uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}

      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPCRAFT_EDGE_TOKEN }}
          snap: ${{ steps.snapcraft.outputs.snap }}
